// src/views/FileView.vue
<script setup lang="ts">
import TextEditor from "@/components/TextEditor.vue";
import {useAppStore} from "@/stores/app";
import TableEditor from "@/components/TableEditor.vue";
import {EditMode} from "@/models/EditMode";

const store = useAppStore();

</script>

<template>
  <TextEditor v-if="store.getSelectedFile()?.editMode === EditMode.Text"/>
  <TableEditor v-if="store.getSelectedFile()?.editMode === EditMode.Table"/>
</template>

// src/components/FileView.tsx
import {FileModel} from "@/models/FileModel";
import {EditMode} from "@/models/EditMode";
import {TextEditor} from "@/components/TextEditor";
import {TableEditor} from "@/components/TableEditor";

export function FileView({file}: {
    file: FileModel
}) {
    return (
        <article>
            {file.editMode === EditMode.Text && <TextEditor file={file}/>}
            {file.editMode === EditMode.Table && <TableEditor file={file}/>}
        </article>
    );
}
