// src/components/OpenFileButton.tsx
import {IconButton} from "@/components/IconButton";
import {faFolderOpen} from '@fortawesome/free-solid-svg-icons';
import {FileModel} from "@/models/FileModel";
import {FileLoaders} from "@/models/FileLoaders";

export function OpenFileButton({onOpen}: {
    onOpen?: (model: FileModel) => void,
}) {
    function onCLick() {
        const input = document.createElement('input');
        input.type = 'file';
        input.accept = FileLoaders.map(it => `.${it.extension},${it.mimeType}`).join(',');
        input.onchange = async () => {
            const file = input.files?.[0];
            if (file) {
                const fileModel = new FileModel(file);
                await fileModel.load();
                onOpen?.(fileModel);
            }
        }
        input.click();
    };

    return (
        <IconButton icon={faFolderOpen} onClick={onCLick}/>
    );
}

// src/components/OpenFileButton.vue
<script setup lang="ts">
import IconButton from "@/components/IconButton.vue";
import {FileModel} from "@/models/FileModel";

const emit = defineEmits<{
  (e: 'open', file: FileModel): void,
}>();

const onCLick = () => {
  const input = document.createElement('input');
  input.type = 'file';
  input.accept = '.csv,text/csv';
  input.onchange = () => {
    const file = input.files?.[0];
    if (file) {
      emit('open', new FileModel(file));
    }
  }
  input.click();
};
</script>

<template>
  <IconButton icon="folder-open" theme="regular" @click="onCLick"/>
</template>
